"""Stable domain contracts shared by all TraceGraph layers."""

from tracegraph.core.contracts import (
    DEFAULT_MAX_HOPS,
    MAX_HOPS,
    Answer,
    AnswerStatus,
    Chunk,
    Claim,
    Document,
    DocumentVersion,
    Entity,
    EvaluationCase,
    Evidence,
    Feedback,
    FeedbackKind,
    FrontierExpansion,
    GraphPath,
    IngestionJob,
    IngestionStatus,
    PathStep,
    PathTruncation,
    Relation,
    TraversalDirection,
)
from tracegraph.core.ports import (
    DocumentRepository,
    DomainAdapter,
    FeedbackRepository,
    GraphRepository,
    Retriever,
)

__all__ = [
    "DEFAULT_MAX_HOPS",
    "MAX_HOPS",
    "Answer",
    "AnswerStatus",
    "Chunk",
    "Claim",
    "Document",
    "DocumentRepository",
    "DocumentVersion",
    "DomainAdapter",
    "Entity",
    "EvaluationCase",
    "Evidence",
    "Feedback",
    "FeedbackKind",
    "FeedbackRepository",
    "FrontierExpansion",
    "GraphPath",
    "GraphRepository",
    "IngestionJob",
    "IngestionStatus",
    "PathStep",
    "PathTruncation",
    "Relation",
    "Retriever",
    "TraversalDirection",
]
